version: "3"
services:
  mariadb:
    image: ghcr.io/linuxserver/mariadb
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - $PWD/mariadb_data:/config
      - $PWD/sql:/config/initdb.d/
  web:
    hostname: web
    build: .
    image: jrcichra/loxodonta
    # volumes:
    # - ${PWD}/components:/app/components
    # - ${PWD}/pages:/app/pages
    # - ${PWD}/assets:/app/assets
    # - ${PWD}/layouts:/app/layouts
    # - ${PWD}/plugins:/app/plugins
    # - ${PWD}/queries:/app/queries
    # - ${PWD}/nuxt.config.js:/app/nuxt.config.js
    ports:
      - 3000:3000
    depends_on:
      - api
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 30s
      timeout: 20s
      retries: 3
  api:
    hostname: api
    build: ./api
    image: jrcichra/loxodonta-server
    # volumes:
    #   - ${PWD}/api/server.js:/app/server.js
    ports:
      - 3001:3001
    depends_on:
      - mariadb
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/graphiql/"]
      interval: 30s
      timeout: 20s
      retries: 3
  minio:
    hostname: minio
    image: minio/minio:RELEASE.2021-02-14T04-01-33Z
    volumes:
      - ${PWD}/minio_data:/data
    command: server /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
