query feed($id: ID!, $top: Int!) { 
  feed(id: $id,top:$top) {
    post_created
    post_text
    post_edited
    post_views
    post_upvotes
    post_downvotes
    post_user {
      user_id
      user_name
      user_status
      user_avatar {
        object_url
      }
    }
  }
}